version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    command: npm run start:dev
    ports:
      - '9000:9000'
    env_file:
      - .env
    networks:
      - networks-base

  postgres:
    image: postgres:latest
    container_name: database
    networks:
      - networks-base
    ports:
      - '5432:5432'
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_USER: 'admin'
      POSTGRES_DB: 'test'
volumes:
  progresDB:
networks:
  networks-base: