export enum SYSTEM_CODE {
    SUCCESS = 'SUCCESS',
    SORRY_SOMETHING_WENT_WRONG = 'SORRY_SOMETHING_WENT_WRONG',
    BAD_REQUEST = 'BAD_REQUEST',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    DATA_NOT_FOUND = 'DATA_NOT_FOUND',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USERNAME_OR_PASSWORD_INVALID = 'USERNAME_OR_PASSWORD_INVALID',
}
